### PR TITLE
JSON output for CLI

### PR DESCRIPTION
**Pull request by konklone**
The CLI tool currently outputs key-value, line by line, e.g.

```
domain: konklone.com
uri: https://konklone.com
government: false
live: true
ssl: true
...
```

This changes the CLI to output pretty-printed JSON instead:

```
{
  "domain": "konklone.com",
  "uri": "https://konklone.com",
  "government": false,
  "live": true,
  "ssl": true,
  ...
```

It's basically just as readable, but can be piped into other things and efficiently saved to disk in a reliably parseable, standard format.

I also:

* updated the CLI test to accommodate the new format
* bumped the Ruby version up to 2.2.0 to fix the build on Travis, which for some reason says 2.1.1 isn't available anymore
* fixed a typo in `.travis.yml` that shouldn't have had any effect anyway

The [build is failing](https://travis-ci.org/benbalter/site-inspector-ruby/builds/49699961), but for reasons that have nothing to do with my work. Maybe DNSSEC doesn't work from the Travis environment? Either way, the tests pass locally.

### CODE REVIEW

**Comment by benbalter** [comment]
If you don't mind changing 2.2.0 to 2.1 (travis shorthand for 2.1.x), more than glad to merge (which may resolve the failing build).

**Comment by konklone** [comment]
I left the `.ruby-version` at 2.2.0, but set the Travis build info to use `2.1`, which selected `2.1.5` during the build process -- which unfortunately [still fails on DNSSec](https://travis-ci.org/benbalter/site-inspector-ruby/builds/49754785).

**Comment by benbalter** [comment]
I give up. Either way, your PR didn't break it. Will clean up on master. Thanks again!

**Comment by konklone** [comment]
Thank _you_!

**Pull request merged**
